### ISSUE TITLE
Linking to files does not work when using namespaces

### ISSUE THREAD

**Issue by mgrsskls** [miyagi-dev/vscode-miyagi#115]
When using paths with namespaces for `$tpl` or `$ref` in mock files, linking to that file does not work.

So, for example

```
// mocks.yaml

cards:
    $tpl: "@patterns/cards"
    $ref: "@patterns/cards"
```

Both values would be a link, but when clicking on them, I get an error that the file could not be found.
